from pyautocad import Autocad, APoint
from d_l import d_l
from d_c import d_c
from d_groove import d_groove,d_groovea
from d_pointline import d_pointline

def gear(acad,d,D,b,xm,ym,m,flag):

    r1=APoint(d/2+xm+2,ym+b/2)
    r2=APoint(d/2+xm+2,ym-b/2)
    r11=APoint(d/2+xm,ym+(b/2-2))
    r12=APoint(d/2+xm,ym-(b/2-2))
    r3=APoint(D/2-m*1.25+xm,ym+b/2)
    r4=APoint(D/2-m*1.25+xm,ym+-b/2)
    r5=APoint(D/2+xm,ym+b/2)
    r6=APoint(D/2+xm,ym+-b/2)
    r7=APoint(D/2+0.5*m+xm,ym+b/2)
    r8=APoint(D/2+0.5*m+xm,ym+-b/2)
    r9=APoint(D/2+m+xm,ym+b/2-0.5*m)
    r10=APoint(D/2+m+xm,ym-b/2+0.5*m)
    d_l(acad,r11,r12)
    d_l(acad,r11,r1)
    d_l(acad,r12,r2)
    d_l(acad,r2,r4)
    d_l(acad,r4,r6)
    d_l(acad,r6,r8)
    d_l(acad,r1,r3)
    d_l(acad,r3,r5)
    d_l(acad,r5,r7)
    d_l(acad,r3,r4)
    d_l(acad,r5,r6)
    d_l(acad,r8,r10)
    d_l(acad,r9,r7)
    d_l(acad,r9,r10)
    l1=APoint(-d/2+xm-2,ym+b/2)
    l2=APoint(-d/2+xm-2,ym+-b/2)
    l11=APoint(-d/2+xm,ym+(b/2-2))
    l12=APoint(-d/2+xm,ym-(b/2-2))
    l3=APoint(-D/2+m*1.25+xm,ym+b/2)
    l4=APoint(-D/2+m*1.25+xm,ym+-b/2)
    l5=APoint(-D/2+xm,ym+b/2)
    l6=APoint(-D/2+xm,ym+-b/2)
    l7=APoint(-D/2-0.5*m+xm,ym+b/2)
    l8=APoint(-D/2-0.5*m+xm,ym+-b/2)
    l9=APoint(-D/2-m+xm,ym+b/2-0.5*m)
    l10=APoint(-D/2-m+xm,ym-b/2+0.5*m)
    d_l(acad,l11,l12)
    d_l(acad,l12,l2)
    d_l(acad,l11,l1)
    d_l(acad,l2,l4)
    d_l(acad,l4,l6)
    d_l(acad,l6,l8)
    d_l(acad,l1,l3)
    d_l(acad,l3,l5)
    d_l(acad,l5,l7)
    d_l(acad,l3,l4)
    d_l(acad,l5,l6)
    d_l(acad,l8,l10)
    d_l(acad,l9,l7)
    d_l(acad,l9,l10)
    d_l(acad,l1,r1)
    d_l(acad,l2,r2)
    d_l(acad,l11,r11)
    d_l(acad,l12,r12)
    if flag:
        hole(acad,xm,ym,d,D,m,b,'l')
        hole(acad,xm,ym,d,D,m,b,'r')

def hole(acad,x,y,d,D,m,b,flag):
    d1=1.6*d
    D1=D-8*m
    D0=0.5*(d1+D1)
    d0=0.25*(D1-d1)
    C=0.3*b
    if flag=='l':
        [l1,r1]=d_pointline(acad,x-D1/2-2,y+b/2,x-d1/2+2,y+b/2)
        [l2,r2]=d_pointline(acad,x-D1/2,y+b/2-2,x-d1/2,y+b/2-2)
        [l3,r3]=d_pointline(acad,x-D1/2,y+C/2,x-d1/2,y+C/2)
        d_l(acad,l1,l2)
        d_l(acad,r1,r2)
        d_l(acad,l3,l2)
        d_l(acad,r3,r2)
        [l4,r4]=d_pointline(acad,x-D1/2-2,y+-b/2,x-d1/2+2,y+-b/2)
        [l5,r5]=d_pointline(acad,x-D1/2,y+-b/2+2,x-d1/2,y+-b/2+2)
        [l6,r6]=d_pointline(acad,x-D1/2,y+-C/2,x-d1/2,y+-C/2)
        d_l(acad,l4,l5)
        d_l(acad,r4,r5)
        d_l(acad,l6,l5)
        d_l(acad,r6,r5)
        [l7,l8]=d_pointline(acad,x-(D0+d0)/2,y+C/2,x-(D0+d0)/2,y+-C/2)
        [r7,r8]=d_pointline(acad,x-(D0-d0)/2,y+C/2,x-(D0-d0)/2,y+-C/2)
        #中心线
        [midu,midd]=d_pointline(acad,x-D0/2,y+(b/2+2),x-D0/2,y-(b/2+2))
    if flag=='r':
        [l1,r1]=d_pointline(acad,x+(D1/2+2),y+b/2,x+(d1/2-2),y+b/2)
        [l2,r2]=d_pointline(acad,x+D1/2,y+b/2-2,x+d1/2,y+b/2-2)
        [l3,r3]=d_pointline(acad,x+D1/2,y+C/2,x+d1/2,y+C/2)
        d_l(acad,l1,l2)
        d_l(acad,r1,r2)
        d_l(acad,l3,l2)
        d_l(acad,r3,r2)
        [l4,r4]=d_pointline(acad,x+(D1/2+2),y+-b/2,x+(d1/2-2),y+-b/2)
        [l5,r5]=d_pointline(acad,x+D1/2,y+-b/2+2,x+d1/2,y+-b/2+2)
        [l6,r6]=d_pointline(acad,x+D1/2,y+-C/2,x+d1/2,y+-C/2)
        d_l(acad,l4,l5)
        d_l(acad,r4,r5)
        d_l(acad,l6,l5)
        d_l(acad,r6,r5)
        [l7,l8]=d_pointline(acad,x+(D0+d0)/2,y+C/2,x+(D0+d0)/2,y+-C/2)
        [r7,r8]=d_pointline(acad,x+(D0-d0)/2,y+C/2,x+(D0-d0)/2,y+-C/2)
        #中心线
        [midu,midd]=d_pointline(acad,x+D0/2,y+(b/2+2),x+D0/2,y-(b/2+2))
